import { Head, router, useForm, usePage } from '@inertiajs/react';
import FullCalendar from '@fullcalendar/react';
import sqLocale from '@fullcalendar/core/locales/sq';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin, { DateClickArg } from '@fullcalendar/interaction';
import type { EventDropArg } from '@fullcalendar/core';
import { Plus } from 'lucide-react';
import { useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import { Badge, Button, Field, Input, Modal, Select } from '../../Components/UI';
import { useTranslation } from '../../lib/i18n';
import type { SharedProps } from '../../types';

const colors: Record<string, string> = { pending: '#ca8a04', confirmed: '#dc2626', completed: '#64748b', cancelled: '#94a3b8', late_cancelled: '#b91c1c', no_show: '#7f1d1d' };
const localInput = (date: Date | string) => { const d = new Date(date); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16); };

export default function Calendar({ reservations, fields }: { reservations: any[]; fields: any[]; timezone: string }) {
    const t = useTranslation(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<any>(null);
    const { locale, flash } = usePage<SharedProps>().props;
    const form = useForm({ customer_name: '', customer_phone: '', football_field_id: fields[0]?.id ?? '', starts_at: '', ends_at: '', status: 'confirmed', payment_status: 'unpaid', paid_amount: 0, is_walk_in: false, notes: '' });
    const showNew = (start = new Date()) => { const end = new Date(start); end.setHours(end.getHours() + 1); setEditing(null); form.setData({ customer_name: '', customer_phone: '', football_field_id: fields[0]?.id ?? '', starts_at: localInput(start), ends_at: localInput(end), status: 'confirmed', payment_status: 'unpaid', paid_amount: 0, is_walk_in: false, notes: '' }); setOpen(true); };
    const showEdit = (r: any) => { setEditing(r); form.setData({ customer_name: r.customer_name, customer_phone: r.customer_phone, football_field_id: r.football_field_id, starts_at: localInput(r.starts_at), ends_at: localInput(r.ends_at), status: r.status, payment_status: r.payment_status, paid_amount: Number(r.paid_amount), is_walk_in: r.is_walk_in, notes: r.notes ?? '' }); setOpen(true); };
    const submit = (e: React.FormEvent) => { e.preventDefault(); if (editing) form.put(`/reservations/${editing.id}`, { onSuccess: () => setOpen(false) }); else form.post('/reservations', { onSuccess: () => setOpen(false) }); };
    const drop = (arg: EventDropArg) => { const r = reservations.find(item => String(item.id) === arg.event.id); if (!r || !arg.event.start || !arg.event.end) return arg.revert(); router.put(`/reservations/${r.id}`, { ...r, football_field_id: r.football_field_id, starts_at: localInput(arg.event.start), ends_at: localInput(arg.event.end) }, { preserveScroll: true, onError: () => arg.revert() }); };
    const events = reservations.map(r => ({ id: String(r.id), title: `${r.customer_name} · ${r.football_field.name}`, start: r.starts_at, end: r.ends_at, backgroundColor: colors[r.status], borderColor: colors[r.status], extendedProps: { reservation: r } }));
    return <AppLayout title={t('calendar')}><Head title={t('calendar')} /><div className="page-header"><div><h1>{t('calendar')}</h1><p>{t('calendarHelp')}</p></div><Button onClick={() => showNew()}><Plus size={18} />{t('newReservation')}</Button></div>
        <section className="panel"><FullCalendar plugins={[timeGridPlugin, interactionPlugin]} locales={[sqLocale]} locale={locale} initialView={window.innerWidth < 768 ? 'timeGridDay' : 'timeGridWeek'} headerToolbar={{ left: 'prev,next today', center: 'title', right: 'timeGridDay,timeGridWeek' }} slotMinTime="12:00:00" slotMaxTime="26:00:00" slotDuration="01:00:00" slotLabelInterval="01:00:00" allDaySlot={false} height="auto" nowIndicator editable selectable dateClick={(arg: DateClickArg) => showNew(arg.date)} eventDrop={drop} events={events} eventDidMount={(info) => { info.el.title = `${info.event.title}\n${info.event.extendedProps.reservation.customer_phone}`; info.el.addEventListener('dblclick', () => showEdit(info.event.extendedProps.reservation)); }} />
        </section>
        <Modal open={open} title={editing ? t('edit') : t('newReservation')} onClose={() => setOpen(false)}><form onSubmit={submit}><div className="form-grid">
            <Field label={t('customerName')} error={form.errors.customer_name} required><Input autoFocus value={form.data.customer_name} onChange={e => form.setData('customer_name', e.target.value)} /></Field><Field label={t('phone')} error={form.errors.customer_phone} required><Input value={form.data.customer_phone} onChange={e => form.setData('customer_phone', e.target.value)} /></Field>
            <Field label={t('selectField')} error={form.errors.football_field_id} required><Select value={form.data.football_field_id} onChange={e => form.setData('football_field_id', Number(e.target.value))}>{fields.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</Select></Field><Field label={t('status')}><Select value={form.data.status} onChange={e => form.setData('status', e.target.value)}><option value="pending">{t('pending')}</option><option value="confirmed">{t('confirmed')}</option><option value="completed">{t('completed')}</option><option value="no_show">{t('noShow')}</option></Select></Field>
            <Field label={t('start')} error={form.errors.starts_at} required><Input type="datetime-local" value={form.data.starts_at} onChange={e => form.setData('starts_at', e.target.value)} /></Field><Field label={t('end')} error={form.errors.ends_at} required><Input type="datetime-local" value={form.data.ends_at} onChange={e => form.setData('ends_at', e.target.value)} /></Field>
            <Field label={t('payment')} error={form.errors.payment_status}><Select value={form.data.payment_status} onChange={e => form.setData('payment_status', e.target.value)}><option value="unpaid">{t('unpaid')}</option><option value="partial">{t('partial')}</option><option value="paid">{t('paid')}</option></Select></Field><Field label={t('amountPaid')}><Input type="number" min="0" step=".01" value={form.data.paid_amount} onChange={e => form.setData('paid_amount', Number(e.target.value))} /></Field>
            <Field label={t('notes')} error={form.errors.notes}><textarea className="input" value={form.data.notes} onChange={e => form.setData('notes', e.target.value)} /></Field><label style={{ alignSelf: 'end', paddingBottom: 12 }}><input type="checkbox" checked={form.data.is_walk_in} onChange={e => form.setData('is_walk_in', e.target.checked)} /> {t('walkIn')}</label>
        </div>{flash.slot_suggestions && flash.slot_suggestions.length > 0 && <div className="panel" style={{ marginTop: 16 }}><strong>{t('suggestedSlots')}</strong><div className="actions" style={{ marginTop: 10, flexWrap: 'wrap' }}>{flash.slot_suggestions.map(slot => <Button key={slot.starts_at} type="button" variant="secondary" onClick={() => { form.setData('starts_at', slot.starts_at); form.setData('ends_at', slot.ends_at); }}>{slot.label}</Button>)}</div></div>}{editing?.customer && <div className="panel" style={{ marginTop: 16 }}><strong>{t('customerHistory')}</strong><p>{editing.customer.total_reservations} {t('reservations').toLowerCase()} · {editing.customer.no_shows} {t('noShows').toLowerCase()} · <Badge value={editing.customer.reliability_status} /></p></div>}<div className="form-actions">{editing && <Button type="button" variant="danger" onClick={() => confirm(t('cancelReservationConfirm')) && router.delete(`/reservations/${editing.id}`, { onSuccess: () => setOpen(false) })}>{t('cancelReservation')}</Button>}<Button type="button" variant="secondary" onClick={() => setOpen(false)}>{t('close')}</Button><Button disabled={form.processing}>{t('save')}</Button></div></form></Modal>
    </AppLayout>;
}
