import { Head, useForm } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import { Badge, Button, EmptyState, Field, Input, Select } from '../../Components/UI';

export default function CustomerShow({ customer, fields }: { customer: any; fields: Array<{ id: number; name: string }> }) {
    const profile = useForm({ name: customer.name, phone: customer.phone, preferred_field_id: customer.preferred_field_id ?? '' });
    const note = useForm({ note: '' });
    return <AppLayout title={customer.name}><Head title={customer.name} /><div className="page-header"><div><h1>{customer.name}</h1><p>{customer.phone}</p></div><Badge value={customer.reliability_status} /></div>
        <section className="metrics-grid"><div className="metric"><span>Total reservations</span><strong>{customer.total_reservations}</strong></div><div className="metric"><span>Completed</span><strong>{customer.completed_reservations}</strong></div><div className="metric"><span>No-shows</span><strong>{customer.no_shows}</strong></div><div className="metric"><span>Late cancellations</span><strong>{customer.late_cancellations}</strong></div></section>
        <div className="content-grid"><section className="panel"><h2>Reservation history</h2>{customer.reservations.length === 0 ? <EmptyState title="No reservations found." /> : <div className="table-wrap"><table><thead><tr><th>Field</th><th>Date</th><th>Status</th><th>Payment</th></tr></thead><tbody>{customer.reservations.map((r: any) => <tr key={r.id}><td>{r.football_field.name}</td><td>{new Date(r.starts_at).toLocaleString()}</td><td><Badge value={r.status} /></td><td><Badge value={r.payment_status} /></td></tr>)}</tbody></table></div>}</section>
            <div style={{ display: 'grid', gap: 18 }}><section className="panel"><h2>Profile</h2><form onSubmit={e => { e.preventDefault(); profile.put(`/customers/${customer.id}`); }} style={{ display: 'grid', gap: 12 }}><Field label="Name" error={profile.errors.name}><Input value={profile.data.name} onChange={e => profile.setData('name', e.target.value)} /></Field><Field label="Phone" error={profile.errors.phone}><Input value={profile.data.phone} onChange={e => profile.setData('phone', e.target.value)} /></Field><Field label="Preferred field"><Select value={profile.data.preferred_field_id} onChange={e => profile.setData('preferred_field_id', e.target.value)}><option value="">None</option>{fields.map(f => <option key={f.id} value={f.id}>{f.name}</option>)}</Select></Field><Button disabled={profile.processing}>Save profile</Button></form></section>
            <section className="panel"><h2>Private notes</h2><form onSubmit={e => { e.preventDefault(); note.post(`/customers/${customer.id}/notes`, { onSuccess: () => note.reset() }); }}><Field label="Add note" error={note.errors.note}><textarea className="input" value={note.data.note} onChange={e => note.setData('note', e.target.value)} /></Field><div className="form-actions"><Button disabled={note.processing}>Add note</Button></div></form>{customer.notes.map((n: any) => <div key={n.id} style={{ padding: '12px 0', borderTop: '1px solid var(--border)' }}><p>{n.note}</p><small>{n.user?.name} · {new Date(n.created_at).toLocaleString()}</small></div>)}</section></div>
        </div>
    </AppLayout>;
}
